### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by AMeng** [mehcode/python-saml#3]
The `README` file just says to look at the tests for examples. Some more user-friendly documentation would be awesome.

**Comment by mehcode** [comment]
Something simple like https://github.com/kvesteri/sqlalchemy-utils/tree/master/docs would be awesome. If you want to get something simple started I could get it up on RTD.

**Comment by AMeng** [comment]
Any opinions on #5?

**Comment by mehcode** [comment]
http://python-saml.readthedocs.org/

**Comment by AMeng** [comment]
:+1:
